version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - website_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - website_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - website_network

  website:
    build: ./requirements/bonus/Website
    container_name: website
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - website_network

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"                   # FTP port
      - "21000-21010:21000-21010" # Passive FTP ports
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/run/vsftpd/data
    networks:
      - website_network

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8800:8800"
    networks:
      - website_network

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - website_network


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ksohail-/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ksohail-/data/wordpress_data
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ksohail-/data/portainer
      o: bind

networks:
  website_network:
    driver: bridge

