version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - website_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - website_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - website_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/volumes/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/volumes/wordpress_data
      o: bind

networks:
  website_network:
    driver: bridge


# services:
#   nginx:
#     build: ./requirements/nginx
#     ports:
#       - "443:443"
#     volumes:
#       - ./requirements/nginx/certs:/etc/nginx/certs
#       - ./requirements/nginx/html:/var/www/html
#     restart: always
#     networks:
#       - website

# networks:
#   website:
#     driver: bridge
